fragment PostParts on Post {
  __typename
  title
  title_en
  slug
  publishedAt
  mainImage
  categories
  body
}

fragment ChiSonoParts on ChiSono {
  __typename
  titolo
  sottotitolo
  descrizione
  fotoProfilo
  esperienze {
    __typename
    anno
    titolo
    titolo_en
    luogo
  }
  filosofiaTitolo
  filosofiaCitazione
  filosofiaAutore
  filosofiaDescrizione
  titolo_en
  sottotitolo_en
  descrizione_en
  filosofiaTitolo_en
  filosofiaCitazione_en
  filosofiaDescrizione_en
}

fragment FotografiaParts on Fotografia {
  __typename
  title
  src
  categoriaString
  description
  description_en
  metadata
  ordine
}

fragment ProgettoVideoParts on ProgettoVideo {
  __typename
  title
  title_en
  src
  categoriaString
  sottocategoria
  description
  description_en
  metadata
  logline
  logline_en
  url
  ordine
}

fragment ContattiParts on Contatti {
  __typename
  email
  telefono
  instagram
  linkedin
  indirizzoStudio
  titoloPagina
  sottotitoloPagina
  titoloSezione
  testoSottoTitolo
  orariRitratto
  orariReportage
  orariRicerca
  titoloPagina_en
  sottotitoloPagina_en
  titoloSezione_en
  testoSottoTitolo_en
  orariRitratto_en
  orariReportage_en
  orariRicerca_en
  formName
  formEmail
  formSubject
  formMessage
  formSubmit
  formName_en
  formSubject_en
  formMessage_en
  formSubmit_en
}

fragment GlobalParts on Global {
  __typename
  email
  telefono
  indirizzo
  copyright
  instagram
  linkedin
  youtube
  facebook
  logoName
  navHome
  navPortfolio
  navBlog
  navAbout
  navContact
  navSubFotografia
  navSubVideomaking
  navSubRegia
  navSubMosaico
  filterFoto1
  filterFoto2
  filterVideoAll
  navAbout_en
  navContact_en
  navSubFotografia_en
  navSubRegia_en
  navSubMosaico_en
  filterFoto1_en
  filterFoto2_en
  filterVideoAll_en
}

fragment HomepageParts on Homepage {
  __typename
  heroBands {
    __typename
    title
    title_en
    href
    images
  }
  chiSonoLabel
  chiSonoPreviewTitle
  chiSonoPreviewText1
  chiSonoPreviewText2
  blogLabel
  mosaicoLabel
  ctaBlog
  ctaMosaico
  chiSonoLabel_en
  chiSonoPreviewTitle_en
  chiSonoPreviewText1_en
  chiSonoPreviewText2_en
  blogLabel_en
  mosaicoLabel_en
  ctaBlog_en
  ctaMosaico_en
}

fragment PortfolioPageParts on PortfolioPage {
  __typename
  tabFotografia
  tabVideomaking
  tabRegia
  tabMosaico
  filterFoto1
  filterFoto2
  filterVideoAll
  filterVideo1
  filterVideo2
  imagesFoto1
  imagesFoto2
  descFoto1
  descFoto2
  tabFotografia_en
  tabRegia_en
  tabMosaico_en
  filterFoto1_en
  filterFoto2_en
  filterVideoAll_en
  filterVideo1_en
  filterVideo2_en
  descFoto1_en
  descFoto2_en
}

fragment BlogPageParts on BlogPage {
  __typename
  attivata
  label
  title
  emptyMessage
  readMoreLabel
  label_en
  title_en
  emptyMessage_en
  readMoreLabel_en
}
