//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post: Post;
  postConnection: PostConnection;
  chiSono: ChiSono;
  chiSonoConnection: ChiSonoConnection;
  fotografia: Fotografia;
  fotografiaConnection: FotografiaConnection;
  progettoVideo: ProgettoVideo;
  progettoVideoConnection: ProgettoVideoConnection;
  contatti: Contatti;
  contattiConnection: ContattiConnection;
  global: Global;
  globalConnection: GlobalConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  portfolioPage: PortfolioPage;
  portfolioPageConnection: PortfolioPageConnection;
  blogPage: BlogPage;
  blogPageConnection: BlogPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryChiSonoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryChiSonoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChiSonoFilter>;
};


export type QueryFotografiaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFotografiaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FotografiaFilter>;
};


export type QueryProgettoVideoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProgettoVideoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgettoVideoFilter>;
};


export type QueryContattiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContattiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContattiFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryPortfolioPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioPageFilter>;
};


export type QueryBlogPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPageFilter>;
};

export type DocumentFilter = {
  post?: InputMaybe<PostFilter>;
  chiSono?: InputMaybe<ChiSonoFilter>;
  fotografia?: InputMaybe<FotografiaFilter>;
  progettoVideo?: InputMaybe<ProgettoVideoFilter>;
  contatti?: InputMaybe<ContattiFilter>;
  global?: InputMaybe<GlobalFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  portfolioPage?: InputMaybe<PortfolioPageFilter>;
  blogPage?: InputMaybe<BlogPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post | ChiSono | Fotografia | ProgettoVideo | Contatti | Global | Homepage | PortfolioPage | BlogPage | Folder;

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  title_en?: Maybe<Scalars['String']['output']>;
  slug: Scalars['String']['output'];
  publishedAt?: Maybe<Scalars['String']['output']>;
  mainImage?: Maybe<Scalars['String']['output']>;
  categories?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  mainImage?: InputMaybe<ImageFilter>;
  categories?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type ChiSonoEsperienze = {
  __typename?: 'ChiSonoEsperienze';
  anno?: Maybe<Scalars['String']['output']>;
  titolo?: Maybe<Scalars['String']['output']>;
  titolo_en?: Maybe<Scalars['String']['output']>;
  luogo?: Maybe<Scalars['String']['output']>;
};

export type ChiSono = Node & Document & {
  __typename?: 'ChiSono';
  titolo: Scalars['String']['output'];
  sottotitolo?: Maybe<Scalars['String']['output']>;
  descrizione?: Maybe<Scalars['JSON']['output']>;
  fotoProfilo?: Maybe<Scalars['String']['output']>;
  esperienze?: Maybe<Array<Maybe<ChiSonoEsperienze>>>;
  filosofiaTitolo?: Maybe<Scalars['String']['output']>;
  filosofiaCitazione?: Maybe<Scalars['String']['output']>;
  filosofiaAutore?: Maybe<Scalars['String']['output']>;
  filosofiaDescrizione?: Maybe<Scalars['String']['output']>;
  titolo_en?: Maybe<Scalars['String']['output']>;
  sottotitolo_en?: Maybe<Scalars['String']['output']>;
  descrizione_en?: Maybe<Scalars['JSON']['output']>;
  filosofiaTitolo_en?: Maybe<Scalars['String']['output']>;
  filosofiaCitazione_en?: Maybe<Scalars['String']['output']>;
  filosofiaDescrizione_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ChiSonoEsperienzeFilter = {
  anno?: InputMaybe<StringFilter>;
  titolo?: InputMaybe<StringFilter>;
  titolo_en?: InputMaybe<StringFilter>;
  luogo?: InputMaybe<StringFilter>;
};

export type ChiSonoFilter = {
  titolo?: InputMaybe<StringFilter>;
  sottotitolo?: InputMaybe<StringFilter>;
  descrizione?: InputMaybe<RichTextFilter>;
  fotoProfilo?: InputMaybe<ImageFilter>;
  esperienze?: InputMaybe<ChiSonoEsperienzeFilter>;
  filosofiaTitolo?: InputMaybe<StringFilter>;
  filosofiaCitazione?: InputMaybe<StringFilter>;
  filosofiaAutore?: InputMaybe<StringFilter>;
  filosofiaDescrizione?: InputMaybe<StringFilter>;
  titolo_en?: InputMaybe<StringFilter>;
  sottotitolo_en?: InputMaybe<StringFilter>;
  descrizione_en?: InputMaybe<RichTextFilter>;
  filosofiaTitolo_en?: InputMaybe<StringFilter>;
  filosofiaCitazione_en?: InputMaybe<StringFilter>;
  filosofiaDescrizione_en?: InputMaybe<StringFilter>;
};

export type ChiSonoConnectionEdges = {
  __typename?: 'ChiSonoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ChiSono>;
};

export type ChiSonoConnection = Connection & {
  __typename?: 'ChiSonoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ChiSonoConnectionEdges>>>;
};

export type Fotografia = Node & Document & {
  __typename?: 'Fotografia';
  title?: Maybe<Scalars['String']['output']>;
  src: Scalars['String']['output'];
  categoriaString: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  description_en?: Maybe<Scalars['String']['output']>;
  metadata?: Maybe<Scalars['String']['output']>;
  ordine?: Maybe<Scalars['Float']['output']>;
  inMosaico?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FotografiaFilter = {
  title?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
  categoriaString?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  metadata?: InputMaybe<StringFilter>;
  ordine?: InputMaybe<NumberFilter>;
  inMosaico?: InputMaybe<BooleanFilter>;
};

export type FotografiaConnectionEdges = {
  __typename?: 'FotografiaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Fotografia>;
};

export type FotografiaConnection = Connection & {
  __typename?: 'FotografiaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FotografiaConnectionEdges>>>;
};

export type ProgettoVideo = Node & Document & {
  __typename?: 'ProgettoVideo';
  title: Scalars['String']['output'];
  title_en?: Maybe<Scalars['String']['output']>;
  src: Scalars['String']['output'];
  categoriaString: Scalars['String']['output'];
  sottocategoria?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  description_en?: Maybe<Scalars['String']['output']>;
  metadata?: Maybe<Scalars['String']['output']>;
  logline?: Maybe<Scalars['String']['output']>;
  logline_en?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  ordine?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProgettoVideoFilter = {
  title?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
  categoriaString?: InputMaybe<StringFilter>;
  sottocategoria?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  metadata?: InputMaybe<StringFilter>;
  logline?: InputMaybe<StringFilter>;
  logline_en?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  ordine?: InputMaybe<NumberFilter>;
};

export type ProgettoVideoConnectionEdges = {
  __typename?: 'ProgettoVideoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ProgettoVideo>;
};

export type ProgettoVideoConnection = Connection & {
  __typename?: 'ProgettoVideoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProgettoVideoConnectionEdges>>>;
};

export type Contatti = Node & Document & {
  __typename?: 'Contatti';
  email: Scalars['String']['output'];
  telefono?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  indirizzoStudio?: Maybe<Scalars['String']['output']>;
  titoloPagina?: Maybe<Scalars['String']['output']>;
  sottotitoloPagina?: Maybe<Scalars['String']['output']>;
  titoloSezione?: Maybe<Scalars['String']['output']>;
  testoSottoTitolo?: Maybe<Scalars['String']['output']>;
  orariRitratto?: Maybe<Scalars['String']['output']>;
  orariReportage?: Maybe<Scalars['String']['output']>;
  orariRicerca?: Maybe<Scalars['String']['output']>;
  titoloPagina_en?: Maybe<Scalars['String']['output']>;
  sottotitoloPagina_en?: Maybe<Scalars['String']['output']>;
  titoloSezione_en?: Maybe<Scalars['String']['output']>;
  testoSottoTitolo_en?: Maybe<Scalars['String']['output']>;
  orariRitratto_en?: Maybe<Scalars['String']['output']>;
  orariReportage_en?: Maybe<Scalars['String']['output']>;
  orariRicerca_en?: Maybe<Scalars['String']['output']>;
  formName?: Maybe<Scalars['String']['output']>;
  formEmail?: Maybe<Scalars['String']['output']>;
  formSubject?: Maybe<Scalars['String']['output']>;
  formMessage?: Maybe<Scalars['String']['output']>;
  formSubmit?: Maybe<Scalars['String']['output']>;
  formName_en?: Maybe<Scalars['String']['output']>;
  formSubject_en?: Maybe<Scalars['String']['output']>;
  formMessage_en?: Maybe<Scalars['String']['output']>;
  formSubmit_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContattiFilter = {
  email?: InputMaybe<StringFilter>;
  telefono?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  indirizzoStudio?: InputMaybe<StringFilter>;
  titoloPagina?: InputMaybe<StringFilter>;
  sottotitoloPagina?: InputMaybe<StringFilter>;
  titoloSezione?: InputMaybe<StringFilter>;
  testoSottoTitolo?: InputMaybe<StringFilter>;
  orariRitratto?: InputMaybe<StringFilter>;
  orariReportage?: InputMaybe<StringFilter>;
  orariRicerca?: InputMaybe<StringFilter>;
  titoloPagina_en?: InputMaybe<StringFilter>;
  sottotitoloPagina_en?: InputMaybe<StringFilter>;
  titoloSezione_en?: InputMaybe<StringFilter>;
  testoSottoTitolo_en?: InputMaybe<StringFilter>;
  orariRitratto_en?: InputMaybe<StringFilter>;
  orariReportage_en?: InputMaybe<StringFilter>;
  orariRicerca_en?: InputMaybe<StringFilter>;
  formName?: InputMaybe<StringFilter>;
  formEmail?: InputMaybe<StringFilter>;
  formSubject?: InputMaybe<StringFilter>;
  formMessage?: InputMaybe<StringFilter>;
  formSubmit?: InputMaybe<StringFilter>;
  formName_en?: InputMaybe<StringFilter>;
  formSubject_en?: InputMaybe<StringFilter>;
  formMessage_en?: InputMaybe<StringFilter>;
  formSubmit_en?: InputMaybe<StringFilter>;
};

export type ContattiConnectionEdges = {
  __typename?: 'ContattiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contatti>;
};

export type ContattiConnection = Connection & {
  __typename?: 'ContattiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContattiConnectionEdges>>>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  email: Scalars['String']['output'];
  telefono?: Maybe<Scalars['String']['output']>;
  indirizzo?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  youtube?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  logoName?: Maybe<Scalars['String']['output']>;
  navHome?: Maybe<Scalars['String']['output']>;
  navPortfolio?: Maybe<Scalars['String']['output']>;
  navBlog?: Maybe<Scalars['String']['output']>;
  navAbout?: Maybe<Scalars['String']['output']>;
  navContact?: Maybe<Scalars['String']['output']>;
  navSubFotografia?: Maybe<Scalars['String']['output']>;
  navSubVideomaking?: Maybe<Scalars['String']['output']>;
  navSubRegia?: Maybe<Scalars['String']['output']>;
  navSubMosaico?: Maybe<Scalars['String']['output']>;
  filterFoto1?: Maybe<Scalars['String']['output']>;
  filterFoto2?: Maybe<Scalars['String']['output']>;
  filterVideoAll?: Maybe<Scalars['String']['output']>;
  navAbout_en?: Maybe<Scalars['String']['output']>;
  navContact_en?: Maybe<Scalars['String']['output']>;
  navSubFotografia_en?: Maybe<Scalars['String']['output']>;
  navSubRegia_en?: Maybe<Scalars['String']['output']>;
  navSubMosaico_en?: Maybe<Scalars['String']['output']>;
  filterFoto1_en?: Maybe<Scalars['String']['output']>;
  filterFoto2_en?: Maybe<Scalars['String']['output']>;
  filterVideoAll_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalFilter = {
  email?: InputMaybe<StringFilter>;
  telefono?: InputMaybe<StringFilter>;
  indirizzo?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  youtube?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  logoName?: InputMaybe<StringFilter>;
  navHome?: InputMaybe<StringFilter>;
  navPortfolio?: InputMaybe<StringFilter>;
  navBlog?: InputMaybe<StringFilter>;
  navAbout?: InputMaybe<StringFilter>;
  navContact?: InputMaybe<StringFilter>;
  navSubFotografia?: InputMaybe<StringFilter>;
  navSubVideomaking?: InputMaybe<StringFilter>;
  navSubRegia?: InputMaybe<StringFilter>;
  navSubMosaico?: InputMaybe<StringFilter>;
  filterFoto1?: InputMaybe<StringFilter>;
  filterFoto2?: InputMaybe<StringFilter>;
  filterVideoAll?: InputMaybe<StringFilter>;
  navAbout_en?: InputMaybe<StringFilter>;
  navContact_en?: InputMaybe<StringFilter>;
  navSubFotografia_en?: InputMaybe<StringFilter>;
  navSubRegia_en?: InputMaybe<StringFilter>;
  navSubMosaico_en?: InputMaybe<StringFilter>;
  filterFoto1_en?: InputMaybe<StringFilter>;
  filterFoto2_en?: InputMaybe<StringFilter>;
  filterVideoAll_en?: InputMaybe<StringFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type HomepageHeroBandsImages = {
  __typename?: 'HomepageHeroBandsImages';
  src: Scalars['String']['output'];
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type HomepageHeroBands = {
  __typename?: 'HomepageHeroBands';
  title?: Maybe<Scalars['String']['output']>;
  title_en?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<HomepageHeroBandsImages>>>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  heroBands?: Maybe<Array<Maybe<HomepageHeroBands>>>;
  chiSonoLabel?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewTitle?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewText1?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewText2?: Maybe<Scalars['String']['output']>;
  blogLabel?: Maybe<Scalars['String']['output']>;
  mosaicoLabel?: Maybe<Scalars['String']['output']>;
  ctaBlog?: Maybe<Scalars['String']['output']>;
  ctaMosaico?: Maybe<Scalars['String']['output']>;
  chiSonoLabel_en?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewTitle_en?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewText1_en?: Maybe<Scalars['String']['output']>;
  chiSonoPreviewText2_en?: Maybe<Scalars['String']['output']>;
  blogLabel_en?: Maybe<Scalars['String']['output']>;
  mosaicoLabel_en?: Maybe<Scalars['String']['output']>;
  ctaBlog_en?: Maybe<Scalars['String']['output']>;
  ctaMosaico_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageHeroBandsImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type HomepageHeroBandsFilter = {
  title?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  images?: InputMaybe<HomepageHeroBandsImagesFilter>;
};

export type HomepageFilter = {
  heroBands?: InputMaybe<HomepageHeroBandsFilter>;
  chiSonoLabel?: InputMaybe<StringFilter>;
  chiSonoPreviewTitle?: InputMaybe<StringFilter>;
  chiSonoPreviewText1?: InputMaybe<StringFilter>;
  chiSonoPreviewText2?: InputMaybe<StringFilter>;
  blogLabel?: InputMaybe<StringFilter>;
  mosaicoLabel?: InputMaybe<StringFilter>;
  ctaBlog?: InputMaybe<StringFilter>;
  ctaMosaico?: InputMaybe<StringFilter>;
  chiSonoLabel_en?: InputMaybe<StringFilter>;
  chiSonoPreviewTitle_en?: InputMaybe<StringFilter>;
  chiSonoPreviewText1_en?: InputMaybe<StringFilter>;
  chiSonoPreviewText2_en?: InputMaybe<StringFilter>;
  blogLabel_en?: InputMaybe<StringFilter>;
  mosaicoLabel_en?: InputMaybe<StringFilter>;
  ctaBlog_en?: InputMaybe<StringFilter>;
  ctaMosaico_en?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type PortfolioPageImagesFoto1 = {
  __typename?: 'PortfolioPageImagesFoto1';
  src: Scalars['String']['output'];
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PortfolioPageImagesFoto2 = {
  __typename?: 'PortfolioPageImagesFoto2';
  src: Scalars['String']['output'];
  objectPosition?: Maybe<Scalars['String']['output']>;
};

export type PortfolioPage = Node & Document & {
  __typename?: 'PortfolioPage';
  tabFotografia?: Maybe<Scalars['String']['output']>;
  tabVideomaking?: Maybe<Scalars['String']['output']>;
  tabRegia?: Maybe<Scalars['String']['output']>;
  tabMosaico?: Maybe<Scalars['String']['output']>;
  filterFoto1?: Maybe<Scalars['String']['output']>;
  filterFoto2?: Maybe<Scalars['String']['output']>;
  filterVideoAll?: Maybe<Scalars['String']['output']>;
  filterVideo1?: Maybe<Scalars['String']['output']>;
  filterVideo2?: Maybe<Scalars['String']['output']>;
  imagesFoto1?: Maybe<Array<Maybe<PortfolioPageImagesFoto1>>>;
  imagesFoto2?: Maybe<Array<Maybe<PortfolioPageImagesFoto2>>>;
  descFoto1?: Maybe<Scalars['String']['output']>;
  descFoto2?: Maybe<Scalars['String']['output']>;
  tabFotografia_en?: Maybe<Scalars['String']['output']>;
  tabRegia_en?: Maybe<Scalars['String']['output']>;
  tabMosaico_en?: Maybe<Scalars['String']['output']>;
  filterFoto1_en?: Maybe<Scalars['String']['output']>;
  filterFoto2_en?: Maybe<Scalars['String']['output']>;
  filterVideoAll_en?: Maybe<Scalars['String']['output']>;
  filterVideo1_en?: Maybe<Scalars['String']['output']>;
  filterVideo2_en?: Maybe<Scalars['String']['output']>;
  descFoto1_en?: Maybe<Scalars['String']['output']>;
  descFoto2_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PortfolioPageImagesFoto1Filter = {
  src?: InputMaybe<ImageFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PortfolioPageImagesFoto2Filter = {
  src?: InputMaybe<ImageFilter>;
  objectPosition?: InputMaybe<StringFilter>;
};

export type PortfolioPageFilter = {
  tabFotografia?: InputMaybe<StringFilter>;
  tabVideomaking?: InputMaybe<StringFilter>;
  tabRegia?: InputMaybe<StringFilter>;
  tabMosaico?: InputMaybe<StringFilter>;
  filterFoto1?: InputMaybe<StringFilter>;
  filterFoto2?: InputMaybe<StringFilter>;
  filterVideoAll?: InputMaybe<StringFilter>;
  filterVideo1?: InputMaybe<StringFilter>;
  filterVideo2?: InputMaybe<StringFilter>;
  imagesFoto1?: InputMaybe<PortfolioPageImagesFoto1Filter>;
  imagesFoto2?: InputMaybe<PortfolioPageImagesFoto2Filter>;
  descFoto1?: InputMaybe<StringFilter>;
  descFoto2?: InputMaybe<StringFilter>;
  tabFotografia_en?: InputMaybe<StringFilter>;
  tabRegia_en?: InputMaybe<StringFilter>;
  tabMosaico_en?: InputMaybe<StringFilter>;
  filterFoto1_en?: InputMaybe<StringFilter>;
  filterFoto2_en?: InputMaybe<StringFilter>;
  filterVideoAll_en?: InputMaybe<StringFilter>;
  filterVideo1_en?: InputMaybe<StringFilter>;
  filterVideo2_en?: InputMaybe<StringFilter>;
  descFoto1_en?: InputMaybe<StringFilter>;
  descFoto2_en?: InputMaybe<StringFilter>;
};

export type PortfolioPageConnectionEdges = {
  __typename?: 'PortfolioPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PortfolioPage>;
};

export type PortfolioPageConnection = Connection & {
  __typename?: 'PortfolioPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioPageConnectionEdges>>>;
};

export type BlogPage = Node & Document & {
  __typename?: 'BlogPage';
  attivata?: Maybe<Scalars['Boolean']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  emptyMessage?: Maybe<Scalars['String']['output']>;
  readMoreLabel?: Maybe<Scalars['String']['output']>;
  label_en?: Maybe<Scalars['String']['output']>;
  title_en?: Maybe<Scalars['String']['output']>;
  emptyMessage_en?: Maybe<Scalars['String']['output']>;
  readMoreLabel_en?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BlogPageFilter = {
  attivata?: InputMaybe<BooleanFilter>;
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  emptyMessage?: InputMaybe<StringFilter>;
  readMoreLabel?: InputMaybe<StringFilter>;
  label_en?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  emptyMessage_en?: InputMaybe<StringFilter>;
  readMoreLabel_en?: InputMaybe<StringFilter>;
};

export type BlogPageConnectionEdges = {
  __typename?: 'BlogPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BlogPage>;
};

export type BlogPageConnection = Connection & {
  __typename?: 'BlogPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost: Post;
  createPost: Post;
  updateChiSono: ChiSono;
  createChiSono: ChiSono;
  updateFotografia: Fotografia;
  createFotografia: Fotografia;
  updateProgettoVideo: ProgettoVideo;
  createProgettoVideo: ProgettoVideo;
  updateContatti: Contatti;
  createContatti: Contatti;
  updateGlobal: Global;
  createGlobal: Global;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updatePortfolioPage: PortfolioPage;
  createPortfolioPage: PortfolioPage;
  updateBlogPage: BlogPage;
  createBlogPage: BlogPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateChiSonoArgs = {
  relativePath: Scalars['String']['input'];
  params: ChiSonoMutation;
};


export type MutationCreateChiSonoArgs = {
  relativePath: Scalars['String']['input'];
  params: ChiSonoMutation;
};


export type MutationUpdateFotografiaArgs = {
  relativePath: Scalars['String']['input'];
  params: FotografiaMutation;
};


export type MutationCreateFotografiaArgs = {
  relativePath: Scalars['String']['input'];
  params: FotografiaMutation;
};


export type MutationUpdateProgettoVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgettoVideoMutation;
};


export type MutationCreateProgettoVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgettoVideoMutation;
};


export type MutationUpdateContattiArgs = {
  relativePath: Scalars['String']['input'];
  params: ContattiMutation;
};


export type MutationCreateContattiArgs = {
  relativePath: Scalars['String']['input'];
  params: ContattiMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdatePortfolioPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioPageMutation;
};


export type MutationCreatePortfolioPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioPageMutation;
};


export type MutationUpdateBlogPageArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPageMutation;
};


export type MutationCreateBlogPageArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPageMutation;
};

export type DocumentUpdateMutation = {
  post?: InputMaybe<PostMutation>;
  chiSono?: InputMaybe<ChiSonoMutation>;
  fotografia?: InputMaybe<FotografiaMutation>;
  progettoVideo?: InputMaybe<ProgettoVideoMutation>;
  contatti?: InputMaybe<ContattiMutation>;
  global?: InputMaybe<GlobalMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  portfolioPage?: InputMaybe<PortfolioPageMutation>;
  blogPage?: InputMaybe<BlogPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post?: InputMaybe<PostMutation>;
  chiSono?: InputMaybe<ChiSonoMutation>;
  fotografia?: InputMaybe<FotografiaMutation>;
  progettoVideo?: InputMaybe<ProgettoVideoMutation>;
  contatti?: InputMaybe<ContattiMutation>;
  global?: InputMaybe<GlobalMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  portfolioPage?: InputMaybe<PortfolioPageMutation>;
  blogPage?: InputMaybe<BlogPageMutation>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  mainImage?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ChiSonoEsperienzeMutation = {
  anno?: InputMaybe<Scalars['String']['input']>;
  titolo?: InputMaybe<Scalars['String']['input']>;
  titolo_en?: InputMaybe<Scalars['String']['input']>;
  luogo?: InputMaybe<Scalars['String']['input']>;
};

export type ChiSonoMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  sottotitolo?: InputMaybe<Scalars['String']['input']>;
  descrizione?: InputMaybe<Scalars['JSON']['input']>;
  fotoProfilo?: InputMaybe<Scalars['String']['input']>;
  esperienze?: InputMaybe<Array<InputMaybe<ChiSonoEsperienzeMutation>>>;
  filosofiaTitolo?: InputMaybe<Scalars['String']['input']>;
  filosofiaCitazione?: InputMaybe<Scalars['String']['input']>;
  filosofiaAutore?: InputMaybe<Scalars['String']['input']>;
  filosofiaDescrizione?: InputMaybe<Scalars['String']['input']>;
  titolo_en?: InputMaybe<Scalars['String']['input']>;
  sottotitolo_en?: InputMaybe<Scalars['String']['input']>;
  descrizione_en?: InputMaybe<Scalars['JSON']['input']>;
  filosofiaTitolo_en?: InputMaybe<Scalars['String']['input']>;
  filosofiaCitazione_en?: InputMaybe<Scalars['String']['input']>;
  filosofiaDescrizione_en?: InputMaybe<Scalars['String']['input']>;
};

export type FotografiaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
  categoriaString?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  metadata?: InputMaybe<Scalars['String']['input']>;
  ordine?: InputMaybe<Scalars['Float']['input']>;
  inMosaico?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProgettoVideoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
  categoriaString?: InputMaybe<Scalars['String']['input']>;
  sottocategoria?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  metadata?: InputMaybe<Scalars['String']['input']>;
  logline?: InputMaybe<Scalars['String']['input']>;
  logline_en?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  ordine?: InputMaybe<Scalars['Float']['input']>;
};

export type ContattiMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  telefono?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  indirizzoStudio?: InputMaybe<Scalars['String']['input']>;
  titoloPagina?: InputMaybe<Scalars['String']['input']>;
  sottotitoloPagina?: InputMaybe<Scalars['String']['input']>;
  titoloSezione?: InputMaybe<Scalars['String']['input']>;
  testoSottoTitolo?: InputMaybe<Scalars['String']['input']>;
  orariRitratto?: InputMaybe<Scalars['String']['input']>;
  orariReportage?: InputMaybe<Scalars['String']['input']>;
  orariRicerca?: InputMaybe<Scalars['String']['input']>;
  titoloPagina_en?: InputMaybe<Scalars['String']['input']>;
  sottotitoloPagina_en?: InputMaybe<Scalars['String']['input']>;
  titoloSezione_en?: InputMaybe<Scalars['String']['input']>;
  testoSottoTitolo_en?: InputMaybe<Scalars['String']['input']>;
  orariRitratto_en?: InputMaybe<Scalars['String']['input']>;
  orariReportage_en?: InputMaybe<Scalars['String']['input']>;
  orariRicerca_en?: InputMaybe<Scalars['String']['input']>;
  formName?: InputMaybe<Scalars['String']['input']>;
  formEmail?: InputMaybe<Scalars['String']['input']>;
  formSubject?: InputMaybe<Scalars['String']['input']>;
  formMessage?: InputMaybe<Scalars['String']['input']>;
  formSubmit?: InputMaybe<Scalars['String']['input']>;
  formName_en?: InputMaybe<Scalars['String']['input']>;
  formSubject_en?: InputMaybe<Scalars['String']['input']>;
  formMessage_en?: InputMaybe<Scalars['String']['input']>;
  formSubmit_en?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  telefono?: InputMaybe<Scalars['String']['input']>;
  indirizzo?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  youtube?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  logoName?: InputMaybe<Scalars['String']['input']>;
  navHome?: InputMaybe<Scalars['String']['input']>;
  navPortfolio?: InputMaybe<Scalars['String']['input']>;
  navBlog?: InputMaybe<Scalars['String']['input']>;
  navAbout?: InputMaybe<Scalars['String']['input']>;
  navContact?: InputMaybe<Scalars['String']['input']>;
  navSubFotografia?: InputMaybe<Scalars['String']['input']>;
  navSubVideomaking?: InputMaybe<Scalars['String']['input']>;
  navSubRegia?: InputMaybe<Scalars['String']['input']>;
  navSubMosaico?: InputMaybe<Scalars['String']['input']>;
  filterFoto1?: InputMaybe<Scalars['String']['input']>;
  filterFoto2?: InputMaybe<Scalars['String']['input']>;
  filterVideoAll?: InputMaybe<Scalars['String']['input']>;
  navAbout_en?: InputMaybe<Scalars['String']['input']>;
  navContact_en?: InputMaybe<Scalars['String']['input']>;
  navSubFotografia_en?: InputMaybe<Scalars['String']['input']>;
  navSubRegia_en?: InputMaybe<Scalars['String']['input']>;
  navSubMosaico_en?: InputMaybe<Scalars['String']['input']>;
  filterFoto1_en?: InputMaybe<Scalars['String']['input']>;
  filterFoto2_en?: InputMaybe<Scalars['String']['input']>;
  filterVideoAll_en?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroBandsImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroBandsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<HomepageHeroBandsImagesMutation>>>;
};

export type HomepageMutation = {
  heroBands?: InputMaybe<Array<InputMaybe<HomepageHeroBandsMutation>>>;
  chiSonoLabel?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewTitle?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewText1?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewText2?: InputMaybe<Scalars['String']['input']>;
  blogLabel?: InputMaybe<Scalars['String']['input']>;
  mosaicoLabel?: InputMaybe<Scalars['String']['input']>;
  ctaBlog?: InputMaybe<Scalars['String']['input']>;
  ctaMosaico?: InputMaybe<Scalars['String']['input']>;
  chiSonoLabel_en?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewTitle_en?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewText1_en?: InputMaybe<Scalars['String']['input']>;
  chiSonoPreviewText2_en?: InputMaybe<Scalars['String']['input']>;
  blogLabel_en?: InputMaybe<Scalars['String']['input']>;
  mosaicoLabel_en?: InputMaybe<Scalars['String']['input']>;
  ctaBlog_en?: InputMaybe<Scalars['String']['input']>;
  ctaMosaico_en?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioPageImagesFoto1Mutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioPageImagesFoto2Mutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  objectPosition?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioPageMutation = {
  tabFotografia?: InputMaybe<Scalars['String']['input']>;
  tabVideomaking?: InputMaybe<Scalars['String']['input']>;
  tabRegia?: InputMaybe<Scalars['String']['input']>;
  tabMosaico?: InputMaybe<Scalars['String']['input']>;
  filterFoto1?: InputMaybe<Scalars['String']['input']>;
  filterFoto2?: InputMaybe<Scalars['String']['input']>;
  filterVideoAll?: InputMaybe<Scalars['String']['input']>;
  filterVideo1?: InputMaybe<Scalars['String']['input']>;
  filterVideo2?: InputMaybe<Scalars['String']['input']>;
  imagesFoto1?: InputMaybe<Array<InputMaybe<PortfolioPageImagesFoto1Mutation>>>;
  imagesFoto2?: InputMaybe<Array<InputMaybe<PortfolioPageImagesFoto2Mutation>>>;
  descFoto1?: InputMaybe<Scalars['String']['input']>;
  descFoto2?: InputMaybe<Scalars['String']['input']>;
  tabFotografia_en?: InputMaybe<Scalars['String']['input']>;
  tabRegia_en?: InputMaybe<Scalars['String']['input']>;
  tabMosaico_en?: InputMaybe<Scalars['String']['input']>;
  filterFoto1_en?: InputMaybe<Scalars['String']['input']>;
  filterFoto2_en?: InputMaybe<Scalars['String']['input']>;
  filterVideoAll_en?: InputMaybe<Scalars['String']['input']>;
  filterVideo1_en?: InputMaybe<Scalars['String']['input']>;
  filterVideo2_en?: InputMaybe<Scalars['String']['input']>;
  descFoto1_en?: InputMaybe<Scalars['String']['input']>;
  descFoto2_en?: InputMaybe<Scalars['String']['input']>;
};

export type BlogPageMutation = {
  attivata?: InputMaybe<Scalars['Boolean']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  emptyMessage?: InputMaybe<Scalars['String']['input']>;
  readMoreLabel?: InputMaybe<Scalars['String']['input']>;
  label_en?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  emptyMessage_en?: InputMaybe<Scalars['String']['input']>;
  readMoreLabel_en?: InputMaybe<Scalars['String']['input']>;
};

export type PostPartsFragment = { __typename: 'Post', title: string, title_en?: string | null, slug: string, publishedAt?: string | null, mainImage?: string | null, categories?: string | null, body?: any | null };

export type ChiSonoPartsFragment = { __typename: 'ChiSono', titolo: string, sottotitolo?: string | null, descrizione?: any | null, fotoProfilo?: string | null, filosofiaTitolo?: string | null, filosofiaCitazione?: string | null, filosofiaAutore?: string | null, filosofiaDescrizione?: string | null, titolo_en?: string | null, sottotitolo_en?: string | null, descrizione_en?: any | null, filosofiaTitolo_en?: string | null, filosofiaCitazione_en?: string | null, filosofiaDescrizione_en?: string | null, esperienze?: Array<{ __typename: 'ChiSonoEsperienze', anno?: string | null, titolo?: string | null, titolo_en?: string | null, luogo?: string | null } | null> | null };

export type FotografiaPartsFragment = { __typename: 'Fotografia', title?: string | null, src: string, categoriaString: string, description?: string | null, description_en?: string | null, metadata?: string | null, ordine?: number | null, inMosaico?: boolean | null };

export type ProgettoVideoPartsFragment = { __typename: 'ProgettoVideo', title: string, title_en?: string | null, src: string, categoriaString: string, sottocategoria?: string | null, description?: string | null, description_en?: string | null, metadata?: string | null, logline?: string | null, logline_en?: string | null, url?: string | null, ordine?: number | null };

export type ContattiPartsFragment = { __typename: 'Contatti', email: string, telefono?: string | null, instagram?: string | null, linkedin?: string | null, indirizzoStudio?: string | null, titoloPagina?: string | null, sottotitoloPagina?: string | null, titoloSezione?: string | null, testoSottoTitolo?: string | null, orariRitratto?: string | null, orariReportage?: string | null, orariRicerca?: string | null, titoloPagina_en?: string | null, sottotitoloPagina_en?: string | null, titoloSezione_en?: string | null, testoSottoTitolo_en?: string | null, orariRitratto_en?: string | null, orariReportage_en?: string | null, orariRicerca_en?: string | null, formName?: string | null, formEmail?: string | null, formSubject?: string | null, formMessage?: string | null, formSubmit?: string | null, formName_en?: string | null, formSubject_en?: string | null, formMessage_en?: string | null, formSubmit_en?: string | null };

export type GlobalPartsFragment = { __typename: 'Global', email: string, telefono?: string | null, indirizzo?: string | null, copyright?: string | null, instagram?: string | null, linkedin?: string | null, youtube?: string | null, facebook?: string | null, logoName?: string | null, navHome?: string | null, navPortfolio?: string | null, navBlog?: string | null, navAbout?: string | null, navContact?: string | null, navSubFotografia?: string | null, navSubVideomaking?: string | null, navSubRegia?: string | null, navSubMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, navAbout_en?: string | null, navContact_en?: string | null, navSubFotografia_en?: string | null, navSubRegia_en?: string | null, navSubMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null };

export type HomepagePartsFragment = { __typename: 'Homepage', chiSonoLabel?: string | null, chiSonoPreviewTitle?: string | null, chiSonoPreviewText1?: string | null, chiSonoPreviewText2?: string | null, blogLabel?: string | null, mosaicoLabel?: string | null, ctaBlog?: string | null, ctaMosaico?: string | null, chiSonoLabel_en?: string | null, chiSonoPreviewTitle_en?: string | null, chiSonoPreviewText1_en?: string | null, chiSonoPreviewText2_en?: string | null, blogLabel_en?: string | null, mosaicoLabel_en?: string | null, ctaBlog_en?: string | null, ctaMosaico_en?: string | null, heroBands?: Array<{ __typename: 'HomepageHeroBands', title?: string | null, title_en?: string | null, href?: string | null, images?: Array<{ __typename: 'HomepageHeroBandsImages', src: string, objectPosition?: string | null } | null> | null } | null> | null };

export type PortfolioPagePartsFragment = { __typename: 'PortfolioPage', tabFotografia?: string | null, tabVideomaking?: string | null, tabRegia?: string | null, tabMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, filterVideo1?: string | null, filterVideo2?: string | null, descFoto1?: string | null, descFoto2?: string | null, tabFotografia_en?: string | null, tabRegia_en?: string | null, tabMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null, filterVideo1_en?: string | null, filterVideo2_en?: string | null, descFoto1_en?: string | null, descFoto2_en?: string | null, imagesFoto1?: Array<{ __typename: 'PortfolioPageImagesFoto1', src: string, objectPosition?: string | null } | null> | null, imagesFoto2?: Array<{ __typename: 'PortfolioPageImagesFoto2', src: string, objectPosition?: string | null } | null> | null };

export type BlogPagePartsFragment = { __typename: 'BlogPage', attivata?: boolean | null, label?: string | null, title?: string | null, emptyMessage?: string | null, readMoreLabel?: string | null, label_en?: string | null, title_en?: string | null, emptyMessage_en?: string | null, readMoreLabel_en?: string | null };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, title_en?: string | null, slug: string, publishedAt?: string | null, mainImage?: string | null, categories?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, title_en?: string | null, slug: string, publishedAt?: string | null, mainImage?: string | null, categories?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ChiSonoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ChiSonoQuery = { __typename?: 'Query', chiSono: { __typename: 'ChiSono', id: string, titolo: string, sottotitolo?: string | null, descrizione?: any | null, fotoProfilo?: string | null, filosofiaTitolo?: string | null, filosofiaCitazione?: string | null, filosofiaAutore?: string | null, filosofiaDescrizione?: string | null, titolo_en?: string | null, sottotitolo_en?: string | null, descrizione_en?: any | null, filosofiaTitolo_en?: string | null, filosofiaCitazione_en?: string | null, filosofiaDescrizione_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, esperienze?: Array<{ __typename: 'ChiSonoEsperienze', anno?: string | null, titolo?: string | null, titolo_en?: string | null, luogo?: string | null } | null> | null } };

export type ChiSonoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ChiSonoFilter>;
}>;


export type ChiSonoConnectionQuery = { __typename?: 'Query', chiSonoConnection: { __typename?: 'ChiSonoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ChiSonoConnectionEdges', cursor: string, node?: { __typename: 'ChiSono', id: string, titolo: string, sottotitolo?: string | null, descrizione?: any | null, fotoProfilo?: string | null, filosofiaTitolo?: string | null, filosofiaCitazione?: string | null, filosofiaAutore?: string | null, filosofiaDescrizione?: string | null, titolo_en?: string | null, sottotitolo_en?: string | null, descrizione_en?: any | null, filosofiaTitolo_en?: string | null, filosofiaCitazione_en?: string | null, filosofiaDescrizione_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, esperienze?: Array<{ __typename: 'ChiSonoEsperienze', anno?: string | null, titolo?: string | null, titolo_en?: string | null, luogo?: string | null } | null> | null } | null } | null> | null } };

export type FotografiaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FotografiaQuery = { __typename?: 'Query', fotografia: { __typename: 'Fotografia', id: string, title?: string | null, src: string, categoriaString: string, description?: string | null, description_en?: string | null, metadata?: string | null, ordine?: number | null, inMosaico?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FotografiaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FotografiaFilter>;
}>;


export type FotografiaConnectionQuery = { __typename?: 'Query', fotografiaConnection: { __typename?: 'FotografiaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FotografiaConnectionEdges', cursor: string, node?: { __typename: 'Fotografia', id: string, title?: string | null, src: string, categoriaString: string, description?: string | null, description_en?: string | null, metadata?: string | null, ordine?: number | null, inMosaico?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProgettoVideoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProgettoVideoQuery = { __typename?: 'Query', progettoVideo: { __typename: 'ProgettoVideo', id: string, title: string, title_en?: string | null, src: string, categoriaString: string, sottocategoria?: string | null, description?: string | null, description_en?: string | null, metadata?: string | null, logline?: string | null, logline_en?: string | null, url?: string | null, ordine?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProgettoVideoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgettoVideoFilter>;
}>;


export type ProgettoVideoConnectionQuery = { __typename?: 'Query', progettoVideoConnection: { __typename?: 'ProgettoVideoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProgettoVideoConnectionEdges', cursor: string, node?: { __typename: 'ProgettoVideo', id: string, title: string, title_en?: string | null, src: string, categoriaString: string, sottocategoria?: string | null, description?: string | null, description_en?: string | null, metadata?: string | null, logline?: string | null, logline_en?: string | null, url?: string | null, ordine?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContattiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContattiQuery = { __typename?: 'Query', contatti: { __typename: 'Contatti', id: string, email: string, telefono?: string | null, instagram?: string | null, linkedin?: string | null, indirizzoStudio?: string | null, titoloPagina?: string | null, sottotitoloPagina?: string | null, titoloSezione?: string | null, testoSottoTitolo?: string | null, orariRitratto?: string | null, orariReportage?: string | null, orariRicerca?: string | null, titoloPagina_en?: string | null, sottotitoloPagina_en?: string | null, titoloSezione_en?: string | null, testoSottoTitolo_en?: string | null, orariRitratto_en?: string | null, orariReportage_en?: string | null, orariRicerca_en?: string | null, formName?: string | null, formEmail?: string | null, formSubject?: string | null, formMessage?: string | null, formSubmit?: string | null, formName_en?: string | null, formSubject_en?: string | null, formMessage_en?: string | null, formSubmit_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContattiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContattiFilter>;
}>;


export type ContattiConnectionQuery = { __typename?: 'Query', contattiConnection: { __typename?: 'ContattiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContattiConnectionEdges', cursor: string, node?: { __typename: 'Contatti', id: string, email: string, telefono?: string | null, instagram?: string | null, linkedin?: string | null, indirizzoStudio?: string | null, titoloPagina?: string | null, sottotitoloPagina?: string | null, titoloSezione?: string | null, testoSottoTitolo?: string | null, orariRitratto?: string | null, orariReportage?: string | null, orariRicerca?: string | null, titoloPagina_en?: string | null, sottotitoloPagina_en?: string | null, titoloSezione_en?: string | null, testoSottoTitolo_en?: string | null, orariRitratto_en?: string | null, orariReportage_en?: string | null, orariRicerca_en?: string | null, formName?: string | null, formEmail?: string | null, formSubject?: string | null, formMessage?: string | null, formSubmit?: string | null, formName_en?: string | null, formSubject_en?: string | null, formMessage_en?: string | null, formSubmit_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, email: string, telefono?: string | null, indirizzo?: string | null, copyright?: string | null, instagram?: string | null, linkedin?: string | null, youtube?: string | null, facebook?: string | null, logoName?: string | null, navHome?: string | null, navPortfolio?: string | null, navBlog?: string | null, navAbout?: string | null, navContact?: string | null, navSubFotografia?: string | null, navSubVideomaking?: string | null, navSubRegia?: string | null, navSubMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, navAbout_en?: string | null, navContact_en?: string | null, navSubFotografia_en?: string | null, navSubRegia_en?: string | null, navSubMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, email: string, telefono?: string | null, indirizzo?: string | null, copyright?: string | null, instagram?: string | null, linkedin?: string | null, youtube?: string | null, facebook?: string | null, logoName?: string | null, navHome?: string | null, navPortfolio?: string | null, navBlog?: string | null, navAbout?: string | null, navContact?: string | null, navSubFotografia?: string | null, navSubVideomaking?: string | null, navSubRegia?: string | null, navSubMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, navAbout_en?: string | null, navContact_en?: string | null, navSubFotografia_en?: string | null, navSubRegia_en?: string | null, navSubMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, chiSonoLabel?: string | null, chiSonoPreviewTitle?: string | null, chiSonoPreviewText1?: string | null, chiSonoPreviewText2?: string | null, blogLabel?: string | null, mosaicoLabel?: string | null, ctaBlog?: string | null, ctaMosaico?: string | null, chiSonoLabel_en?: string | null, chiSonoPreviewTitle_en?: string | null, chiSonoPreviewText1_en?: string | null, chiSonoPreviewText2_en?: string | null, blogLabel_en?: string | null, mosaicoLabel_en?: string | null, ctaBlog_en?: string | null, ctaMosaico_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroBands?: Array<{ __typename: 'HomepageHeroBands', title?: string | null, title_en?: string | null, href?: string | null, images?: Array<{ __typename: 'HomepageHeroBandsImages', src: string, objectPosition?: string | null } | null> | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, chiSonoLabel?: string | null, chiSonoPreviewTitle?: string | null, chiSonoPreviewText1?: string | null, chiSonoPreviewText2?: string | null, blogLabel?: string | null, mosaicoLabel?: string | null, ctaBlog?: string | null, ctaMosaico?: string | null, chiSonoLabel_en?: string | null, chiSonoPreviewTitle_en?: string | null, chiSonoPreviewText1_en?: string | null, chiSonoPreviewText2_en?: string | null, blogLabel_en?: string | null, mosaicoLabel_en?: string | null, ctaBlog_en?: string | null, ctaMosaico_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroBands?: Array<{ __typename: 'HomepageHeroBands', title?: string | null, title_en?: string | null, href?: string | null, images?: Array<{ __typename: 'HomepageHeroBandsImages', src: string, objectPosition?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type PortfolioPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioPageQuery = { __typename?: 'Query', portfolioPage: { __typename: 'PortfolioPage', id: string, tabFotografia?: string | null, tabVideomaking?: string | null, tabRegia?: string | null, tabMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, filterVideo1?: string | null, filterVideo2?: string | null, descFoto1?: string | null, descFoto2?: string | null, tabFotografia_en?: string | null, tabRegia_en?: string | null, tabMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null, filterVideo1_en?: string | null, filterVideo2_en?: string | null, descFoto1_en?: string | null, descFoto2_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, imagesFoto1?: Array<{ __typename: 'PortfolioPageImagesFoto1', src: string, objectPosition?: string | null } | null> | null, imagesFoto2?: Array<{ __typename: 'PortfolioPageImagesFoto2', src: string, objectPosition?: string | null } | null> | null } };

export type PortfolioPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioPageFilter>;
}>;


export type PortfolioPageConnectionQuery = { __typename?: 'Query', portfolioPageConnection: { __typename?: 'PortfolioPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioPageConnectionEdges', cursor: string, node?: { __typename: 'PortfolioPage', id: string, tabFotografia?: string | null, tabVideomaking?: string | null, tabRegia?: string | null, tabMosaico?: string | null, filterFoto1?: string | null, filterFoto2?: string | null, filterVideoAll?: string | null, filterVideo1?: string | null, filterVideo2?: string | null, descFoto1?: string | null, descFoto2?: string | null, tabFotografia_en?: string | null, tabRegia_en?: string | null, tabMosaico_en?: string | null, filterFoto1_en?: string | null, filterFoto2_en?: string | null, filterVideoAll_en?: string | null, filterVideo1_en?: string | null, filterVideo2_en?: string | null, descFoto1_en?: string | null, descFoto2_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, imagesFoto1?: Array<{ __typename: 'PortfolioPageImagesFoto1', src: string, objectPosition?: string | null } | null> | null, imagesFoto2?: Array<{ __typename: 'PortfolioPageImagesFoto2', src: string, objectPosition?: string | null } | null> | null } | null } | null> | null } };

export type BlogPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogPageQuery = { __typename?: 'Query', blogPage: { __typename: 'BlogPage', id: string, attivata?: boolean | null, label?: string | null, title?: string | null, emptyMessage?: string | null, readMoreLabel?: string | null, label_en?: string | null, title_en?: string | null, emptyMessage_en?: string | null, readMoreLabel_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPageFilter>;
}>;


export type BlogPageConnectionQuery = { __typename?: 'Query', blogPageConnection: { __typename?: 'BlogPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogPageConnectionEdges', cursor: string, node?: { __typename: 'BlogPage', id: string, attivata?: boolean | null, label?: string | null, title?: string | null, emptyMessage?: string | null, readMoreLabel?: string | null, label_en?: string | null, title_en?: string | null, emptyMessage_en?: string | null, readMoreLabel_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  title_en
  slug
  publishedAt
  mainImage
  categories
  body
}
    `;
export const ChiSonoPartsFragmentDoc = gql`
    fragment ChiSonoParts on ChiSono {
  __typename
  titolo
  sottotitolo
  descrizione
  fotoProfilo
  esperienze {
    __typename
    anno
    titolo
    titolo_en
    luogo
  }
  filosofiaTitolo
  filosofiaCitazione
  filosofiaAutore
  filosofiaDescrizione
  titolo_en
  sottotitolo_en
  descrizione_en
  filosofiaTitolo_en
  filosofiaCitazione_en
  filosofiaDescrizione_en
}
    `;
export const FotografiaPartsFragmentDoc = gql`
    fragment FotografiaParts on Fotografia {
  __typename
  title
  src
  categoriaString
  description
  description_en
  metadata
  ordine
  inMosaico
}
    `;
export const ProgettoVideoPartsFragmentDoc = gql`
    fragment ProgettoVideoParts on ProgettoVideo {
  __typename
  title
  title_en
  src
  categoriaString
  sottocategoria
  description
  description_en
  metadata
  logline
  logline_en
  url
  ordine
}
    `;
export const ContattiPartsFragmentDoc = gql`
    fragment ContattiParts on Contatti {
  __typename
  email
  telefono
  instagram
  linkedin
  indirizzoStudio
  titoloPagina
  sottotitoloPagina
  titoloSezione
  testoSottoTitolo
  orariRitratto
  orariReportage
  orariRicerca
  titoloPagina_en
  sottotitoloPagina_en
  titoloSezione_en
  testoSottoTitolo_en
  orariRitratto_en
  orariReportage_en
  orariRicerca_en
  formName
  formEmail
  formSubject
  formMessage
  formSubmit
  formName_en
  formSubject_en
  formMessage_en
  formSubmit_en
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  email
  telefono
  indirizzo
  copyright
  instagram
  linkedin
  youtube
  facebook
  logoName
  navHome
  navPortfolio
  navBlog
  navAbout
  navContact
  navSubFotografia
  navSubVideomaking
  navSubRegia
  navSubMosaico
  filterFoto1
  filterFoto2
  filterVideoAll
  navAbout_en
  navContact_en
  navSubFotografia_en
  navSubRegia_en
  navSubMosaico_en
  filterFoto1_en
  filterFoto2_en
  filterVideoAll_en
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  heroBands {
    __typename
    title
    title_en
    href
    images {
      __typename
      src
      objectPosition
    }
  }
  chiSonoLabel
  chiSonoPreviewTitle
  chiSonoPreviewText1
  chiSonoPreviewText2
  blogLabel
  mosaicoLabel
  ctaBlog
  ctaMosaico
  chiSonoLabel_en
  chiSonoPreviewTitle_en
  chiSonoPreviewText1_en
  chiSonoPreviewText2_en
  blogLabel_en
  mosaicoLabel_en
  ctaBlog_en
  ctaMosaico_en
}
    `;
export const PortfolioPagePartsFragmentDoc = gql`
    fragment PortfolioPageParts on PortfolioPage {
  __typename
  tabFotografia
  tabVideomaking
  tabRegia
  tabMosaico
  filterFoto1
  filterFoto2
  filterVideoAll
  filterVideo1
  filterVideo2
  imagesFoto1 {
    __typename
    src
    objectPosition
  }
  imagesFoto2 {
    __typename
    src
    objectPosition
  }
  descFoto1
  descFoto2
  tabFotografia_en
  tabRegia_en
  tabMosaico_en
  filterFoto1_en
  filterFoto2_en
  filterVideoAll_en
  filterVideo1_en
  filterVideo2_en
  descFoto1_en
  descFoto2_en
}
    `;
export const BlogPagePartsFragmentDoc = gql`
    fragment BlogPageParts on BlogPage {
  __typename
  attivata
  label
  title
  emptyMessage
  readMoreLabel
  label_en
  title_en
  emptyMessage_en
  readMoreLabel_en
}
    `;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const ChiSonoDocument = gql`
    query chiSono($relativePath: String!) {
  chiSono(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ChiSonoParts
  }
}
    ${ChiSonoPartsFragmentDoc}`;
export const ChiSonoConnectionDocument = gql`
    query chiSonoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ChiSonoFilter) {
  chiSonoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ChiSonoParts
      }
    }
  }
}
    ${ChiSonoPartsFragmentDoc}`;
export const FotografiaDocument = gql`
    query fotografia($relativePath: String!) {
  fotografia(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FotografiaParts
  }
}
    ${FotografiaPartsFragmentDoc}`;
export const FotografiaConnectionDocument = gql`
    query fotografiaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FotografiaFilter) {
  fotografiaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FotografiaParts
      }
    }
  }
}
    ${FotografiaPartsFragmentDoc}`;
export const ProgettoVideoDocument = gql`
    query progettoVideo($relativePath: String!) {
  progettoVideo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProgettoVideoParts
  }
}
    ${ProgettoVideoPartsFragmentDoc}`;
export const ProgettoVideoConnectionDocument = gql`
    query progettoVideoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProgettoVideoFilter) {
  progettoVideoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProgettoVideoParts
      }
    }
  }
}
    ${ProgettoVideoPartsFragmentDoc}`;
export const ContattiDocument = gql`
    query contatti($relativePath: String!) {
  contatti(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContattiParts
  }
}
    ${ContattiPartsFragmentDoc}`;
export const ContattiConnectionDocument = gql`
    query contattiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContattiFilter) {
  contattiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContattiParts
      }
    }
  }
}
    ${ContattiPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const PortfolioPageDocument = gql`
    query portfolioPage($relativePath: String!) {
  portfolioPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioPageParts
  }
}
    ${PortfolioPagePartsFragmentDoc}`;
export const PortfolioPageConnectionDocument = gql`
    query portfolioPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioPageFilter) {
  portfolioPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioPageParts
      }
    }
  }
}
    ${PortfolioPagePartsFragmentDoc}`;
export const BlogPageDocument = gql`
    query blogPage($relativePath: String!) {
  blogPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogPageParts
  }
}
    ${BlogPagePartsFragmentDoc}`;
export const BlogPageConnectionDocument = gql`
    query blogPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogPageFilter) {
  blogPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogPageParts
      }
    }
  }
}
    ${BlogPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    chiSono(variables: ChiSonoQueryVariables, options?: C): Promise<{data: ChiSonoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSonoQueryVariables, query: string}> {
        return requester<{data: ChiSonoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSonoQueryVariables, query: string}, ChiSonoQueryVariables>(ChiSonoDocument, variables, options);
      },
    chiSonoConnection(variables?: ChiSonoConnectionQueryVariables, options?: C): Promise<{data: ChiSonoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSonoConnectionQueryVariables, query: string}> {
        return requester<{data: ChiSonoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ChiSonoConnectionQueryVariables, query: string}, ChiSonoConnectionQueryVariables>(ChiSonoConnectionDocument, variables, options);
      },
    fotografia(variables: FotografiaQueryVariables, options?: C): Promise<{data: FotografiaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FotografiaQueryVariables, query: string}> {
        return requester<{data: FotografiaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FotografiaQueryVariables, query: string}, FotografiaQueryVariables>(FotografiaDocument, variables, options);
      },
    fotografiaConnection(variables?: FotografiaConnectionQueryVariables, options?: C): Promise<{data: FotografiaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FotografiaConnectionQueryVariables, query: string}> {
        return requester<{data: FotografiaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FotografiaConnectionQueryVariables, query: string}, FotografiaConnectionQueryVariables>(FotografiaConnectionDocument, variables, options);
      },
    progettoVideo(variables: ProgettoVideoQueryVariables, options?: C): Promise<{data: ProgettoVideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgettoVideoQueryVariables, query: string}> {
        return requester<{data: ProgettoVideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgettoVideoQueryVariables, query: string}, ProgettoVideoQueryVariables>(ProgettoVideoDocument, variables, options);
      },
    progettoVideoConnection(variables?: ProgettoVideoConnectionQueryVariables, options?: C): Promise<{data: ProgettoVideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgettoVideoConnectionQueryVariables, query: string}> {
        return requester<{data: ProgettoVideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgettoVideoConnectionQueryVariables, query: string}, ProgettoVideoConnectionQueryVariables>(ProgettoVideoConnectionDocument, variables, options);
      },
    contatti(variables: ContattiQueryVariables, options?: C): Promise<{data: ContattiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiQueryVariables, query: string}> {
        return requester<{data: ContattiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiQueryVariables, query: string}, ContattiQueryVariables>(ContattiDocument, variables, options);
      },
    contattiConnection(variables?: ContattiConnectionQueryVariables, options?: C): Promise<{data: ContattiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiConnectionQueryVariables, query: string}> {
        return requester<{data: ContattiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContattiConnectionQueryVariables, query: string}, ContattiConnectionQueryVariables>(ContattiConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    portfolioPage(variables: PortfolioPageQueryVariables, options?: C): Promise<{data: PortfolioPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioPageQueryVariables, query: string}> {
        return requester<{data: PortfolioPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioPageQueryVariables, query: string}, PortfolioPageQueryVariables>(PortfolioPageDocument, variables, options);
      },
    portfolioPageConnection(variables?: PortfolioPageConnectionQueryVariables, options?: C): Promise<{data: PortfolioPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioPageConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioPageConnectionQueryVariables, query: string}, PortfolioPageConnectionQueryVariables>(PortfolioPageConnectionDocument, variables, options);
      },
    blogPage(variables: BlogPageQueryVariables, options?: C): Promise<{data: BlogPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPageQueryVariables, query: string}> {
        return requester<{data: BlogPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPageQueryVariables, query: string}, BlogPageQueryVariables>(BlogPageDocument, variables, options);
      },
    blogPageConnection(variables?: BlogPageConnectionQueryVariables, options?: C): Promise<{data: BlogPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPageConnectionQueryVariables, query: string}> {
        return requester<{data: BlogPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPageConnectionQueryVariables, query: string}, BlogPageConnectionQueryVariables>(BlogPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  